language: cpp

compiler:
  - gcc

script:
  - ./configure

before_script:
  - sudo add-apt-repository --yes ppa:smspillaz/cmake-2.8.12
  - sudo apt-get update -qq
  - sudo apt-get install -q -y cmake-data cmake
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq libhdf5-dev
  - gcc --version && g++ --version
  - pwd

after_script:
  - ls -laRh
