language: cpp

compiler:
  - gcc

script:
  - ./configure.sh

before_script:
  - sudo add-apt-repository --yes ppa:smspillaz/cmake-3.0.2
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:fkrull/deadsnakes
  - sudo add-apt-repository --yes ppa:chris-lea/python-numpy
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake-data cmake
  - sudo apt-get install -qq build-essential
  - sudo apt-get install libhdf5-mpi-dev
  - sudo apt-get install python3.4-dev
  - sudo apt-get install python3
  - sudo apt-get install python-numpy
  - sudo apt-get install g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - gcc --version && g++ --version
  - ls -laR /usr/include/python*
  - cd /usr/lib/python3/dist-packages/numpy/core/include/numpy
  - ls -la
  - ls -laHR /usr/include/python3.2mu/*

after_script:
  - ls -laRh
